# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-28 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=500)),
                ('sub_heading', models.CharField(max_length=1000)),
                ('content', models.CharField(max_length=2000)),
                ('background_image', models.CharField(max_length=500)),
                ('posted_by', models.CharField(max_length=100)),
                ('posted_on', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=1000)),
                ('background_image', models.CharField(max_length=500)),
                ('user_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('token', models.IntegerField(max_length=10)),
            ],
        ),
    ]
